# 1. Create a 3x3x3 array with random values 

In [3]:
import numpy as np

a = np.random.random((3,3,3))
print(a)

[[[0.93948068 0.44348017 0.80161939]
  [0.67696838 0.41879714 0.14123655]
  [0.19039712 0.46751407 0.66260308]]

 [[0.47333789 0.65008552 0.60715141]
  [0.32481257 0.21932254 0.74980761]
  [0.40570024 0.23965376 0.70491231]]

 [[0.92498224 0.47295435 0.64477613]
  [0.01158854 0.00977729 0.01570109]
  [0.18227541 0.37365682 0.21024046]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
a = np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [6]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.18158457 -1.12040246 -0.75991059  1.29787462  1.66795747]
 [-0.25092927  0.62680306 -1.41532694  0.22448319 -0.80472904]
 [ 1.29643706 -0.37800875  0.63778761  1.13596077 -0.64247016]
 [ 0.23529863  0.79451547  0.52138957 -0.73877449  1.13177668]
 [-1.18821915 -1.34137606 -1.42525494  1.62685629 -0.95015399]]


# 5.  How to find common values between two arrays?

In [7]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 2 4 5 7]


# 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-07-28
2020-07-29
2020-07-30


# 7. Consider two random array A and B, check if they are equal

In [9]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [10]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.87514952 0.54840852 0.69185206 0.62802593 0.         0.90646387
 0.03972012 0.11045421 0.24903887 0.2469433 ]


# 9. How to print all the values of an array?

In [11]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [12]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)

Y1 = X - X.mean(axis=1).reshape(-1, 1)

print(Y)
print(Y1)

[[ 0.21552838  0.34548525 -0.194652   -0.07900711 -0.12239989  0.02121361
  -0.3128332   0.10832249 -0.10202737  0.12036985]
 [-0.49249132 -0.36883011  0.46120152  0.25929725 -0.09801814  0.04167099
  -0.19389451 -0.03100276  0.02133691  0.40073018]
 [-0.04414457 -0.31727538  0.34453901  0.28692177 -0.36644733  0.27482395
  -0.59913767  0.07082347  0.33901319  0.01088356]
 [ 0.05877553  0.16883032  0.29318805 -0.07278746  0.35360641  0.37767633
  -0.43346923 -0.04474783 -0.46382551 -0.23724661]
 [-0.1700461   0.00249507 -0.10221148 -0.40082758  0.1458214  -0.27624469
   0.15233429  0.30827149  0.3324479   0.00795969]]
[[ 0.21552838  0.34548525 -0.194652   -0.07900711 -0.12239989  0.02121361
  -0.3128332   0.10832249 -0.10202737  0.12036985]
 [-0.49249132 -0.36883011  0.46120152  0.25929725 -0.09801814  0.04167099
  -0.19389451 -0.03100276  0.02133691  0.40073018]
 [-0.04414457 -0.31727538  0.34453901  0.28692177 -0.36644733  0.27482395
  -0.59913767  0.07082347  0.33901319  0.01088356]

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [13]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 2. 2. 3. 6. 3. 2. 1. 2. 5.]


In [14]:
np.add.at(Z, I, 1)
print(Z)

[ 7.  3.  3.  5. 11.  5.  3.  1.  3.  9.]


# 12.How to get the diagonal of a dot product?

In [15]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)

prod1=np.diag(np.dot(A, B))

prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.57916467 0.3743725  0.33091446 0.40927642 0.33508404]
 [0.67397751 0.61183094 0.93421404 0.319653   0.47643023]
 [0.97014771 0.6047213  0.84139435 0.15991201 0.73227642]
 [0.81268951 0.97004384 0.52458378 0.11320214 0.73785278]
 [0.83376756 0.48640332 0.42450806 0.47274943 0.30524931]]
[[0.22199248 0.93710473 0.55959637 0.80408561 0.69605581]
 [0.21945203 0.33151265 0.59127454 0.88971071 0.74384658]
 [0.22791659 0.33858714 0.08639341 0.21470995 0.74489137]
 [0.35648708 0.61275509 0.15962081 0.63840025 0.52007582]
 [0.86163699 0.67349335 0.07381729 0.314642   0.86460649]]
diagonal of a dot product method 1 is.... [0.72077046 1.66747167 1.05271833 1.93359144 1.76815667]
diagonal of a dot product method 2 is.... [0.72077046 1.66747167 1.05271833 1.93359144 1.76815667]


# 13.How to find the most frequent value in an array?

In [16]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[4 3 0 5 3 5 5 4 2 9 7 9 1 0 0 6 9 3 7 2 7 9 0 6 7 1 1 1 8 0 9 7 3 8 8 4 1
 9 1 5 1 3 1 6 0 1 5 8 6 4]
1


# 14.How to get the n largest values of an array

In [17]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])


[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [18]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
